name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        days: 
            - 'day01'
            - 'day02'
            - 'day03'
            - 'day04'
            - 'day05'
            - 'day06'
            - 'day07'
            #- 'day08'
            #- 'day09'
            #- 'day10'
            #- 'day11'
            #- 'day12'
            #- 'day13'
            #- 'day14'
            #- 'day15'
            #- 'day16'
            #- 'day17'
            #- 'day18'
            #- 'day19'
            #- 'day20'
            #- 'day21'
            #- 'day22'
            #- 'day23'
            #- 'day24'
            #- 'day25'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test ./${{matrix.days}}